name: Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Install
        run: yarn install
      - name: Build
        run: yarn build
      - name: Tests
        run: yarn test
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          PUBLIC_KEY: ${{ secrets.PUBLIC_KEY }}
          TOKEN: ${{ secrets.TOKEN }}
          PORT: 8080
